execute:
  daemon: false
  warning: false

jupyter: python3